//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entities.Migrations.Initial", typeof(Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAM1X227bOBB9X6D/QPA5NePkZTeQW6ROswi2ToIq7TstjR2ivGhJKrC/bR/2k/oLO5SoiyXbSYNiUeQlouZy5sycofz9n3+T9xslyRNYJ4ye0enklBLQmcmFXs9o6Vdvf6fv3735LfmYqw352tidBzv01G5GH70vLhhz2SMo7iZKZNY4s/KTzCjGc8POTk//YNMpAwxBMRYhyedSe6GgesDHudEZFL7kcmFykC6e45u0ikpuuQJX8Axm9CN6egGOkkspOOZPQa4o4Vobzz2iu/jiIPXW6HVa4AGXD9sC0G7FpYOI+qIzf2kBp2ehANY5NqGy0nmjfjDg9Dwywobur+KVtowhZxVD21B1xRtS9sGYb5QMM13MpQ1WHaeTyvKENM8nbcdxMMLfCZmX0pcWZhpKb7k8IfflUorsL9g+mG+gZ7qUso8G8eC7nQM8uremAOu3n2EVMd7klLBdPzZ0bN16PnUBN9qfn1Fyi8n5UkLb7F6xqTcW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
